# example .gitpod.yml from https://github.com/gitpod-io/demo-multi-repo-frontend
additionalRepositories:
  - url: https://github.com/gitpod-io/demo-multi-repo-backend
    # checkoutLocation is relative to /workspaces
    checkoutLocation: vbtc

gitConfig:
  alias.s: status
  alias.c: commit
  alias.ca: commit --amend
  alias.f: fetch
  alias.lg: log --oneline
