additionalRepositories:
  - url: https://github.com/VeriBlock/vbk-ri-btc
    # checkoutLocation is relative to /workspaces
    checkoutLocation: /vbtc

gitConfig:
  alias.s: status
  alias.c: commit
  alias.ca: commit --amend
  alias.f: fetch
  alias.lg: log --oneline
