extraction:
  cpp:
    prepare:
      packages:
        - g++-6
    after_prepare:
      - export GIT=true
    configure:
      command:
        - cmake . -Bbuild
    before_index:
      - export GTEST_DIR=$LGTM_SRC/googletest
    index:
      build_command:
        - cmake --build build --parallel 2