var annotated_dup =
[
    [ "altintegration", "namespacealtintegration.html", [
      [ "adaptors", null, [
        [ "BlockIteratorImpl", "structaltintegration_1_1adaptors_1_1BlockIteratorImpl.html", "structaltintegration_1_1adaptors_1_1BlockIteratorImpl" ],
        [ "BlockReaderImpl", "structaltintegration_1_1adaptors_1_1BlockReaderImpl.html", "structaltintegration_1_1adaptors_1_1BlockReaderImpl" ],
        [ "BlockBatchImpl", "structaltintegration_1_1adaptors_1_1BlockBatchImpl.html", "structaltintegration_1_1adaptors_1_1BlockBatchImpl" ],
        [ "InmemStorageIterator", "structaltintegration_1_1adaptors_1_1InmemStorageIterator.html", "structaltintegration_1_1adaptors_1_1InmemStorageIterator" ],
        [ "InmemWriteBatch", "structaltintegration_1_1adaptors_1_1InmemWriteBatch.html", "structaltintegration_1_1adaptors_1_1InmemWriteBatch" ],
        [ "InmemStorageImpl", "structaltintegration_1_1adaptors_1_1InmemStorageImpl.html", "structaltintegration_1_1adaptors_1_1InmemStorageImpl" ],
        [ "LevelDBStorageIterator", "structaltintegration_1_1adaptors_1_1LevelDBStorageIterator.html", "structaltintegration_1_1adaptors_1_1LevelDBStorageIterator" ],
        [ "LevelDBWriteBatch", "structaltintegration_1_1adaptors_1_1LevelDBWriteBatch.html", "structaltintegration_1_1adaptors_1_1LevelDBWriteBatch" ],
        [ "LevelDBStorage", "structaltintegration_1_1adaptors_1_1LevelDBStorage.html", "structaltintegration_1_1adaptors_1_1LevelDBStorage" ],
        [ "PayloadsStorageImpl", "structaltintegration_1_1adaptors_1_1PayloadsStorageImpl.html", "structaltintegration_1_1adaptors_1_1PayloadsStorageImpl" ],
        [ "RocksDBStorageIterator", "structaltintegration_1_1adaptors_1_1RocksDBStorageIterator.html", "structaltintegration_1_1adaptors_1_1RocksDBStorageIterator" ],
        [ "RocksDBWriteBatch", "structaltintegration_1_1adaptors_1_1RocksDBWriteBatch.html", "structaltintegration_1_1adaptors_1_1RocksDBWriteBatch" ],
        [ "RocksDBStorage", "structaltintegration_1_1adaptors_1_1RocksDBStorage.html", "structaltintegration_1_1adaptors_1_1RocksDBStorage" ],
        [ "StorageIterator", "structaltintegration_1_1adaptors_1_1StorageIterator.html", "structaltintegration_1_1adaptors_1_1StorageIterator" ],
        [ "WriteBatch", "structaltintegration_1_1adaptors_1_1WriteBatch.html", "structaltintegration_1_1adaptors_1_1WriteBatch" ],
        [ "Storage", "structaltintegration_1_1adaptors_1_1Storage.html", "structaltintegration_1_1adaptors_1_1Storage" ]
      ] ],
      [ "btc", null, [
        [ "BlockHeader", "structaltintegration_1_1btc_1_1BlockHeader.html", "structaltintegration_1_1btc_1_1BlockHeader" ],
        [ "Block", "structaltintegration_1_1btc_1_1Block.html", "structaltintegration_1_1btc_1_1Block" ],
        [ "BlockLocator", "structaltintegration_1_1btc_1_1BlockLocator.html", "structaltintegration_1_1btc_1_1BlockLocator" ],
        [ "deserialize_type", "structaltintegration_1_1btc_1_1deserialize__type.html", null ],
        [ "CheckVarIntMode", "structaltintegration_1_1btc_1_1CheckVarIntMode.html", "structaltintegration_1_1btc_1_1CheckVarIntMode" ],
        [ "CVarInt", "classaltintegration_1_1btc_1_1CVarInt.html", "classaltintegration_1_1btc_1_1CVarInt" ],
        [ "BigEndian", "classaltintegration_1_1btc_1_1BigEndian.html", "classaltintegration_1_1btc_1_1BigEndian" ],
        [ "CCompactSize", "classaltintegration_1_1btc_1_1CCompactSize.html", "classaltintegration_1_1btc_1_1CCompactSize" ],
        [ "LimitedString", "classaltintegration_1_1btc_1_1LimitedString.html", "classaltintegration_1_1btc_1_1LimitedString" ],
        [ "CSerActionSerialize", "structaltintegration_1_1btc_1_1CSerActionSerialize.html", "structaltintegration_1_1btc_1_1CSerActionSerialize" ],
        [ "CSerActionUnserialize", "structaltintegration_1_1btc_1_1CSerActionUnserialize.html", "structaltintegration_1_1btc_1_1CSerActionUnserialize" ],
        [ "CSizeComputer", "classaltintegration_1_1btc_1_1CSizeComputer.html", "classaltintegration_1_1btc_1_1CSizeComputer" ],
        [ "OutPoint", "structaltintegration_1_1btc_1_1OutPoint.html", "structaltintegration_1_1btc_1_1OutPoint" ],
        [ "TxIn", "structaltintegration_1_1btc_1_1TxIn.html", "structaltintegration_1_1btc_1_1TxIn" ],
        [ "TxOut", "structaltintegration_1_1btc_1_1TxOut.html", "structaltintegration_1_1btc_1_1TxOut" ],
        [ "Transaction", "structaltintegration_1_1btc_1_1Transaction.html", "structaltintegration_1_1btc_1_1Transaction" ]
      ] ],
      [ "cache", null, [
        [ "SmallLFRUCache", "structaltintegration_1_1cache_1_1SmallLFRUCache.html", "structaltintegration_1_1cache_1_1SmallLFRUCache" ]
      ] ],
      [ "signals", null, [
        [ "Connection", "structaltintegration_1_1signals_1_1Connection.html", "structaltintegration_1_1signals_1_1Connection" ]
      ] ],
      [ "ArithUint256", "classaltintegration_1_1ArithUint256.html", "classaltintegration_1_1ArithUint256" ],
      [ "Blob", "structaltintegration_1_1Blob.html", "structaltintegration_1_1Blob" ],
      [ "AltBlockTree", "structaltintegration_1_1AltBlockTree.html", "structaltintegration_1_1AltBlockTree" ],
      [ "PopPayoutsParams", "structaltintegration_1_1PopPayoutsParams.html", "structaltintegration_1_1PopPayoutsParams" ],
      [ "AltChainParams", "structaltintegration_1_1AltChainParams.html", "structaltintegration_1_1AltChainParams" ],
      [ "AltChainParamsRegTest", "structaltintegration_1_1AltChainParamsRegTest.html", "structaltintegration_1_1AltChainParamsRegTest" ],
      [ "BaseBlockTree", "structaltintegration_1_1BaseBlockTree.html", "structaltintegration_1_1BaseBlockTree" ],
      [ "BlockIndex", "structaltintegration_1_1BlockIndex.html", "structaltintegration_1_1BlockIndex" ],
      [ "BlockTree", "structaltintegration_1_1BlockTree.html", "structaltintegration_1_1BlockTree" ],
      [ "BtcChainParams", "structaltintegration_1_1BtcChainParams.html", "structaltintegration_1_1BtcChainParams" ],
      [ "BtcChainParamsMain", "structaltintegration_1_1BtcChainParamsMain.html", "structaltintegration_1_1BtcChainParamsMain" ],
      [ "BtcChainParamsTest", "structaltintegration_1_1BtcChainParamsTest.html", "structaltintegration_1_1BtcChainParamsTest" ],
      [ "BtcChainParamsRegTest", "structaltintegration_1_1BtcChainParamsRegTest.html", "structaltintegration_1_1BtcChainParamsRegTest" ],
      [ "Chain", "structaltintegration_1_1Chain.html", "structaltintegration_1_1Chain" ],
      [ "ChainSlice", "structaltintegration_1_1ChainSlice.html", "structaltintegration_1_1ChainSlice" ],
      [ "AltCommandGroupStore", "structaltintegration_1_1AltCommandGroupStore.html", "structaltintegration_1_1AltCommandGroupStore" ],
      [ "CheckPublicationData", "structaltintegration_1_1CheckPublicationData.html", "structaltintegration_1_1CheckPublicationData" ],
      [ "VbkCommandGroupStore", "structaltintegration_1_1VbkCommandGroupStore.html", "structaltintegration_1_1VbkCommandGroupStore" ],
      [ "VbkBlockTree", "structaltintegration_1_1VbkBlockTree.html", "structaltintegration_1_1VbkBlockTree" ],
      [ "VbkChainParams", "structaltintegration_1_1VbkChainParams.html", "structaltintegration_1_1VbkChainParams" ],
      [ "VbkChainParamsMain", "structaltintegration_1_1VbkChainParamsMain.html", "structaltintegration_1_1VbkChainParamsMain" ],
      [ "VbkChainParamsTest", "structaltintegration_1_1VbkChainParamsTest.html", "structaltintegration_1_1VbkChainParamsTest" ],
      [ "VbkChainParamsRegTest", "structaltintegration_1_1VbkChainParamsRegTest.html", "structaltintegration_1_1VbkChainParamsRegTest" ],
      [ "Config", "structaltintegration_1_1Config.html", "structaltintegration_1_1Config" ],
      [ "vblake_ctx", "namespacealtintegration.html#structaltintegration_1_1vblake__ctx", "namespacealtintegration_structaltintegration_1_1vblake__ctx_dup" ],
      [ "Address", "structaltintegration_1_1Address.html", "structaltintegration_1_1Address" ],
      [ "AltBlock", "structaltintegration_1_1AltBlock.html", "structaltintegration_1_1AltBlock" ],
      [ "ATV", "structaltintegration_1_1ATV.html", "structaltintegration_1_1ATV" ],
      [ "BtcBlock", "structaltintegration_1_1BtcBlock.html", "structaltintegration_1_1BtcBlock" ],
      [ "BtcTx", "structaltintegration_1_1BtcTx.html", "structaltintegration_1_1BtcTx" ],
      [ "Coin", "structaltintegration_1_1Coin.html", "structaltintegration_1_1Coin" ],
      [ "ContextInfoContainer", "structaltintegration_1_1ContextInfoContainer.html", "structaltintegration_1_1ContextInfoContainer" ],
      [ "AuthenticatedContextInfoContainer", "structaltintegration_1_1AuthenticatedContextInfoContainer.html", "structaltintegration_1_1AuthenticatedContextInfoContainer" ],
      [ "Endorsement", "structaltintegration_1_1Endorsement.html", "structaltintegration_1_1Endorsement" ],
      [ "KeystoneContainer", "structaltintegration_1_1KeystoneContainer.html", "structaltintegration_1_1KeystoneContainer" ],
      [ "MerklePath", "structaltintegration_1_1MerklePath.html", "structaltintegration_1_1MerklePath" ],
      [ "VbkNetworkType", "structaltintegration_1_1VbkNetworkType.html", "structaltintegration_1_1VbkNetworkType" ],
      [ "NetworkBytePair", "namespacealtintegration.html#structaltintegration_1_1NetworkBytePair", "namespacealtintegration_structaltintegration_1_1NetworkBytePair_dup" ],
      [ "Output", "structaltintegration_1_1Output.html", "structaltintegration_1_1Output" ],
      [ "PopPayouts", "structaltintegration_1_1PopPayouts.html", "structaltintegration_1_1PopPayouts" ],
      [ "PopData", "structaltintegration_1_1PopData.html", "structaltintegration_1_1PopData" ],
      [ "PublicationData", "structaltintegration_1_1PublicationData.html", "structaltintegration_1_1PublicationData" ],
      [ "VbkMerklePath", "structaltintegration_1_1VbkMerklePath.html", "structaltintegration_1_1VbkMerklePath" ],
      [ "VbkBlock", "structaltintegration_1_1VbkBlock.html", "structaltintegration_1_1VbkBlock" ],
      [ "VbkPopTx", "structaltintegration_1_1VbkPopTx.html", "structaltintegration_1_1VbkPopTx" ],
      [ "VbkTx", "structaltintegration_1_1VbkTx.html", "structaltintegration_1_1VbkTx" ],
      [ "VTB", "structaltintegration_1_1VTB.html", "structaltintegration_1_1VTB" ],
      [ "StateCorruptedException", "structaltintegration_1_1StateCorruptedException.html", "structaltintegration_1_1StateCorruptedException" ],
      [ "StorageIOException", "structaltintegration_1_1StorageIOException.html", "structaltintegration_1_1StorageIOException" ],
      [ "Finalizer", "structaltintegration_1_1Finalizer.html", "structaltintegration_1_1Finalizer" ],
      [ "Logger", "structaltintegration_1_1Logger.html", "structaltintegration_1_1Logger" ],
      [ "MemPool", "structaltintegration_1_1MemPool.html", "structaltintegration_1_1MemPool" ],
      [ "MempoolResult", "namespacealtintegration.html#structaltintegration_1_1MempoolResult", "namespacealtintegration_structaltintegration_1_1MempoolResult_dup" ],
      [ "PopContext", "structaltintegration_1_1PopContext.html", "structaltintegration_1_1PopContext" ],
      [ "ReadStream", "structaltintegration_1_1ReadStream.html", "structaltintegration_1_1ReadStream" ],
      [ "reverse_range", "classaltintegration_1_1reverse__range.html", "classaltintegration_1_1reverse__range" ],
      [ "DefaultPopRewardsCalculator", "structaltintegration_1_1DefaultPopRewardsCalculator.html", "structaltintegration_1_1DefaultPopRewardsCalculator" ],
      [ "PopRewardsCalculator", "structaltintegration_1_1PopRewardsCalculator.html", "structaltintegration_1_1PopRewardsCalculator" ],
      [ "PopRewardsCurveParams", "structaltintegration_1_1PopRewardsCurveParams.html", "structaltintegration_1_1PopRewardsCurveParams" ],
      [ "PopRewardsParams", "structaltintegration_1_1PopRewardsParams.html", "structaltintegration_1_1PopRewardsParams" ],
      [ "BlockBatch", "structaltintegration_1_1BlockBatch.html", "structaltintegration_1_1BlockBatch" ],
      [ "BlockIterator", "structaltintegration_1_1BlockIterator.html", "structaltintegration_1_1BlockIterator" ],
      [ "BlockReader", "structaltintegration_1_1BlockReader.html", "structaltintegration_1_1BlockReader" ],
      [ "PayloadsStorage", "structaltintegration_1_1PayloadsStorage.html", "structaltintegration_1_1PayloadsStorage" ],
      [ "StoredBlockIndex", "structaltintegration_1_1StoredBlockIndex.html", "structaltintegration_1_1StoredBlockIndex" ],
      [ "IsPopPayload", "structaltintegration_1_1IsPopPayload.html", "structaltintegration_1_1IsPopPayload" ],
      [ "ValidationState", "classaltintegration_1_1ValidationState.html", "classaltintegration_1_1ValidationState" ],
      [ "WriteStream", "classaltintegration_1_1WriteStream.html", "classaltintegration_1_1WriteStream" ]
    ] ],
    [ "fmt", null, [
      [ "formatter< altintegration::Blob< N > >", "structfmt_1_1formatter_3_01altintegration_1_1Blob_3_01N_01_4_01_4.html", "structfmt_1_1formatter_3_01altintegration_1_1Blob_3_01N_01_4_01_4" ]
    ] ]
];