var annotated_dup =
[
    [ "altintegration", "namespacealtintegration.html", [
      [ "adaptors", null, [
        [ "BlockBatchImpl", "structaltintegration_1_1adaptors_1_1BlockBatchImpl.html", "structaltintegration_1_1adaptors_1_1BlockBatchImpl" ],
        [ "BlockIteratorImpl", "structaltintegration_1_1adaptors_1_1BlockIteratorImpl.html", "structaltintegration_1_1adaptors_1_1BlockIteratorImpl" ],
        [ "BlockReaderImpl", "structaltintegration_1_1adaptors_1_1BlockReaderImpl.html", null ],
        [ "EthashCacheImpl", "structaltintegration_1_1adaptors_1_1EthashCacheImpl.html", null ],
        [ "InmemStorageImpl", "structaltintegration_1_1adaptors_1_1InmemStorageImpl.html", null ],
        [ "InmemStorageIterator", "structaltintegration_1_1adaptors_1_1InmemStorageIterator.html", null ],
        [ "InmemWriteBatch", "structaltintegration_1_1adaptors_1_1InmemWriteBatch.html", null ],
        [ "LevelDBStorage", "structaltintegration_1_1adaptors_1_1LevelDBStorage.html", null ],
        [ "LevelDBStorageIterator", "structaltintegration_1_1adaptors_1_1LevelDBStorageIterator.html", null ],
        [ "LevelDBWriteBatch", "structaltintegration_1_1adaptors_1_1LevelDBWriteBatch.html", null ],
        [ "PayloadsStorageImpl", "structaltintegration_1_1adaptors_1_1PayloadsStorageImpl.html", "structaltintegration_1_1adaptors_1_1PayloadsStorageImpl" ],
        [ "ProgpowHeaderCacheImpl", "structaltintegration_1_1adaptors_1_1ProgpowHeaderCacheImpl.html", null ],
        [ "RocksDBStorage", "structaltintegration_1_1adaptors_1_1RocksDBStorage.html", null ],
        [ "RocksDBStorageIterator", "structaltintegration_1_1adaptors_1_1RocksDBStorageIterator.html", null ],
        [ "RocksDBWriteBatch", "structaltintegration_1_1adaptors_1_1RocksDBWriteBatch.html", null ],
        [ "Storage", "structaltintegration_1_1adaptors_1_1Storage.html", null ],
        [ "StorageIterator", "structaltintegration_1_1adaptors_1_1StorageIterator.html", null ],
        [ "WriteBatch", "structaltintegration_1_1adaptors_1_1WriteBatch.html", null ]
      ] ],
      [ "btc", null, [
        [ "Address", "structaltintegration_1_1btc_1_1Address.html", null ],
        [ "AddrMsg", "structaltintegration_1_1btc_1_1AddrMsg.html", null ],
        [ "BanEntry", "structaltintegration_1_1btc_1_1BanEntry.html", null ],
        [ "BigEndian", "classaltintegration_1_1btc_1_1BigEndian.html", null ],
        [ "Block", "structaltintegration_1_1btc_1_1Block.html", null ],
        [ "BlockHeader", "structaltintegration_1_1btc_1_1BlockHeader.html", null ],
        [ "BlockHeaderAndShortTxIDs", "structaltintegration_1_1btc_1_1BlockHeaderAndShortTxIDs.html", null ],
        [ "BlockLocator", "structaltintegration_1_1btc_1_1BlockLocator.html", null ],
        [ "BlockMsg", "structaltintegration_1_1btc_1_1BlockMsg.html", null ],
        [ "BlockTransactions", "structaltintegration_1_1btc_1_1BlockTransactions.html", null ],
        [ "BlockTransactionsRequest", "structaltintegration_1_1btc_1_1BlockTransactionsRequest.html", null ],
        [ "BlockTxnMsg", "structaltintegration_1_1btc_1_1BlockTxnMsg.html", null ],
        [ "BloomFilter", "structaltintegration_1_1btc_1_1BloomFilter.html", null ],
        [ "CCompactSize", "classaltintegration_1_1btc_1_1CCompactSize.html", null ],
        [ "CheckVarIntMode", "structaltintegration_1_1btc_1_1CheckVarIntMode.html", null ],
        [ "CmpctBlockMsg", "structaltintegration_1_1btc_1_1CmpctBlockMsg.html", null ],
        [ "CSerActionSerialize", "structaltintegration_1_1btc_1_1CSerActionSerialize.html", null ],
        [ "CSerActionUnserialize", "structaltintegration_1_1btc_1_1CSerActionUnserialize.html", null ],
        [ "CSizeComputer", "classaltintegration_1_1btc_1_1CSizeComputer.html", "classaltintegration_1_1btc_1_1CSizeComputer" ],
        [ "CVarInt", "classaltintegration_1_1btc_1_1CVarInt.html", null ],
        [ "deserialize_type", "structaltintegration_1_1btc_1_1deserialize__type.html", null ],
        [ "FeeFilterMsg", "structaltintegration_1_1btc_1_1FeeFilterMsg.html", null ],
        [ "FilterAddMsg", "structaltintegration_1_1btc_1_1FilterAddMsg.html", null ],
        [ "FilterLoadMsg", "structaltintegration_1_1btc_1_1FilterLoadMsg.html", null ],
        [ "GetBlocksMsg", "structaltintegration_1_1btc_1_1GetBlocksMsg.html", null ],
        [ "GetBlockTxnMsg", "structaltintegration_1_1btc_1_1GetBlockTxnMsg.html", null ],
        [ "GetDataMsg", "structaltintegration_1_1btc_1_1GetDataMsg.html", null ],
        [ "GetHeadersMsg", "structaltintegration_1_1btc_1_1GetHeadersMsg.html", null ],
        [ "Inv", "structaltintegration_1_1btc_1_1Inv.html", null ],
        [ "InvMsg", "structaltintegration_1_1btc_1_1InvMsg.html", null ],
        [ "LimitedString", "classaltintegration_1_1btc_1_1LimitedString.html", null ],
        [ "NetAddr", "structaltintegration_1_1btc_1_1NetAddr.html", null ],
        [ "NotFoundMsg", "structaltintegration_1_1btc_1_1NotFoundMsg.html", null ],
        [ "OutPoint", "structaltintegration_1_1btc_1_1OutPoint.html", null ],
        [ "PrefilledTransaction", "structaltintegration_1_1btc_1_1PrefilledTransaction.html", null ],
        [ "SendCmpctMsg", "structaltintegration_1_1btc_1_1SendCmpctMsg.html", null ],
        [ "Service", "structaltintegration_1_1btc_1_1Service.html", null ],
        [ "SubNet", "structaltintegration_1_1btc_1_1SubNet.html", "structaltintegration_1_1btc_1_1SubNet" ],
        [ "Transaction", "structaltintegration_1_1btc_1_1Transaction.html", null ],
        [ "TxIn", "structaltintegration_1_1btc_1_1TxIn.html", "structaltintegration_1_1btc_1_1TxIn" ],
        [ "TxMsg", "structaltintegration_1_1btc_1_1TxMsg.html", null ],
        [ "TxOut", "structaltintegration_1_1btc_1_1TxOut.html", null ]
      ] ],
      [ "cache", null, [
        [ "SmallLFRUCache", "structaltintegration_1_1cache_1_1SmallLFRUCache.html", null ]
      ] ],
      [ "signals", null, [
        [ "Connection", "structaltintegration_1_1signals_1_1Connection.html", null ]
      ] ],
      [ "Address", "structaltintegration_1_1Address.html", "structaltintegration_1_1Address" ],
      [ "AltBlock", "structaltintegration_1_1AltBlock.html", "structaltintegration_1_1AltBlock" ],
      [ "AltBlockTree", "structaltintegration_1_1AltBlockTree.html", "structaltintegration_1_1AltBlockTree" ],
      [ "AltChainParams", "structaltintegration_1_1AltChainParams.html", "structaltintegration_1_1AltChainParams" ],
      [ "AltChainParamsRegTest", "structaltintegration_1_1AltChainParamsRegTest.html", "structaltintegration_1_1AltChainParamsRegTest" ],
      [ "AltCommandGroupStore", "structaltintegration_1_1AltCommandGroupStore.html", "structaltintegration_1_1AltCommandGroupStore" ],
      [ "ArithUint256", "classaltintegration_1_1ArithUint256.html", "classaltintegration_1_1ArithUint256" ],
      [ "ATV", "structaltintegration_1_1ATV.html", "structaltintegration_1_1ATV" ],
      [ "AuthenticatedContextInfoContainer", "structaltintegration_1_1AuthenticatedContextInfoContainer.html", "structaltintegration_1_1AuthenticatedContextInfoContainer" ],
      [ "BaseBlockTree", "structaltintegration_1_1BaseBlockTree.html", "structaltintegration_1_1BaseBlockTree" ],
      [ "Blob", "structaltintegration_1_1Blob.html", null ],
      [ "BlockBatch", "structaltintegration_1_1BlockBatch.html", "structaltintegration_1_1BlockBatch" ],
      [ "BlockIndex", "structaltintegration_1_1BlockIndex.html", "structaltintegration_1_1BlockIndex" ],
      [ "BlockIterator", "structaltintegration_1_1BlockIterator.html", "structaltintegration_1_1BlockIterator" ],
      [ "BlockReader", "structaltintegration_1_1BlockReader.html", null ],
      [ "BlockTree", "structaltintegration_1_1BlockTree.html", "structaltintegration_1_1BlockTree" ],
      [ "BtcBlock", "structaltintegration_1_1BtcBlock.html", "structaltintegration_1_1BtcBlock" ],
      [ "BtcChainParams", "structaltintegration_1_1BtcChainParams.html", "structaltintegration_1_1BtcChainParams" ],
      [ "BtcChainParamsMain", "structaltintegration_1_1BtcChainParamsMain.html", "structaltintegration_1_1BtcChainParamsMain" ],
      [ "BtcChainParamsRegTest", "structaltintegration_1_1BtcChainParamsRegTest.html", "structaltintegration_1_1BtcChainParamsRegTest" ],
      [ "BtcChainParamsTest", "structaltintegration_1_1BtcChainParamsTest.html", "structaltintegration_1_1BtcChainParamsTest" ],
      [ "BtcTx", "structaltintegration_1_1BtcTx.html", "structaltintegration_1_1BtcTx" ],
      [ "CacheEntry", "structaltintegration_1_1CacheEntry.html", null ],
      [ "Chain", "structaltintegration_1_1Chain.html", null ],
      [ "ChainSlice", "structaltintegration_1_1ChainSlice.html", null ],
      [ "CheckPublicationData", "structaltintegration_1_1CheckPublicationData.html", null ],
      [ "Coin", "structaltintegration_1_1Coin.html", "structaltintegration_1_1Coin" ],
      [ "Config", "structaltintegration_1_1Config.html", "structaltintegration_1_1Config" ],
      [ "ContextInfoContainer", "structaltintegration_1_1ContextInfoContainer.html", "structaltintegration_1_1ContextInfoContainer" ],
      [ "DefaultPopRewardsCalculator", "structaltintegration_1_1DefaultPopRewardsCalculator.html", "structaltintegration_1_1DefaultPopRewardsCalculator" ],
      [ "Endorsement", "structaltintegration_1_1Endorsement.html", null ],
      [ "EthashCache", "structaltintegration_1_1EthashCache.html", null ],
      [ "EthashCacheI", "structaltintegration_1_1EthashCacheI.html", null ],
      [ "FinalizedPayloadsIndex", "structaltintegration_1_1FinalizedPayloadsIndex.html", null ],
      [ "Finalizer", "structaltintegration_1_1Finalizer.html", null ],
      [ "IsPopPayload", "structaltintegration_1_1IsPopPayload.html", null ],
      [ "KeystoneContainer", "structaltintegration_1_1KeystoneContainer.html", null ],
      [ "Logger", "structaltintegration_1_1Logger.html", null ],
      [ "MemPool", "structaltintegration_1_1MemPool.html", "structaltintegration_1_1MemPool" ],
      [ "MempoolResult", "namespacealtintegration.html#structaltintegration_1_1MempoolResult", null ],
      [ "MerklePath", "structaltintegration_1_1MerklePath.html", "structaltintegration_1_1MerklePath" ],
      [ "NetworkBytePair", "namespacealtintegration.html#structaltintegration_1_1NetworkBytePair", "namespacealtintegration_structaltintegration_1_1NetworkBytePair_dup" ],
      [ "Output", "structaltintegration_1_1Output.html", "structaltintegration_1_1Output" ],
      [ "PayloadsIndex", "structaltintegration_1_1PayloadsIndex.html", null ],
      [ "PayloadsStorage", "structaltintegration_1_1PayloadsStorage.html", "structaltintegration_1_1PayloadsStorage" ],
      [ "PopContext", "structaltintegration_1_1PopContext.html", "structaltintegration_1_1PopContext" ],
      [ "PopData", "structaltintegration_1_1PopData.html", "structaltintegration_1_1PopData" ],
      [ "PopPayouts", "structaltintegration_1_1PopPayouts.html", "structaltintegration_1_1PopPayouts" ],
      [ "PopPayoutsParams", "structaltintegration_1_1PopPayoutsParams.html", "structaltintegration_1_1PopPayoutsParams" ],
      [ "PopRewardsCalculator", "structaltintegration_1_1PopRewardsCalculator.html", "structaltintegration_1_1PopRewardsCalculator" ],
      [ "PopRewardsCurveParams", "structaltintegration_1_1PopRewardsCurveParams.html", null ],
      [ "PopRewardsParams", "structaltintegration_1_1PopRewardsParams.html", null ],
      [ "ProgpowHeaderCache", "structaltintegration_1_1ProgpowHeaderCache.html", null ],
      [ "ProgpowHeaderCacheI", "structaltintegration_1_1ProgpowHeaderCacheI.html", null ],
      [ "PublicationData", "structaltintegration_1_1PublicationData.html", "structaltintegration_1_1PublicationData" ],
      [ "ReadStream", "structaltintegration_1_1ReadStream.html", "structaltintegration_1_1ReadStream" ],
      [ "reverse_range", "classaltintegration_1_1reverse__range.html", null ],
      [ "Slice", "structaltintegration_1_1Slice.html", null ],
      [ "StateCorruptedException", "structaltintegration_1_1StateCorruptedException.html", null ],
      [ "StorageIOException", "structaltintegration_1_1StorageIOException.html", null ],
      [ "StoredBlockIndex", "structaltintegration_1_1StoredBlockIndex.html", "structaltintegration_1_1StoredBlockIndex" ],
      [ "ValidationState", "classaltintegration_1_1ValidationState.html", "classaltintegration_1_1ValidationState" ],
      [ "VbkBlock", "structaltintegration_1_1VbkBlock.html", "structaltintegration_1_1VbkBlock" ],
      [ "VbkBlockTree", "structaltintegration_1_1VbkBlockTree.html", "structaltintegration_1_1VbkBlockTree" ],
      [ "VbkChainParams", "structaltintegration_1_1VbkChainParams.html", "structaltintegration_1_1VbkChainParams" ],
      [ "VbkChainParamsMain", "structaltintegration_1_1VbkChainParamsMain.html", "structaltintegration_1_1VbkChainParamsMain" ],
      [ "VbkChainParamsRegTest", "structaltintegration_1_1VbkChainParamsRegTest.html", "structaltintegration_1_1VbkChainParamsRegTest" ],
      [ "VbkChainParamsTest", "structaltintegration_1_1VbkChainParamsTest.html", "structaltintegration_1_1VbkChainParamsTest" ],
      [ "VbkCommandGroupStore", "structaltintegration_1_1VbkCommandGroupStore.html", "structaltintegration_1_1VbkCommandGroupStore" ],
      [ "VbkMerklePath", "structaltintegration_1_1VbkMerklePath.html", "structaltintegration_1_1VbkMerklePath" ],
      [ "VbkNetworkType", "structaltintegration_1_1VbkNetworkType.html", "structaltintegration_1_1VbkNetworkType" ],
      [ "VbkPopTx", "structaltintegration_1_1VbkPopTx.html", "structaltintegration_1_1VbkPopTx" ],
      [ "VbkTx", "structaltintegration_1_1VbkTx.html", "structaltintegration_1_1VbkTx" ],
      [ "vblake_ctx", "namespacealtintegration.html#structaltintegration_1_1vblake__ctx", "namespacealtintegration_structaltintegration_1_1vblake__ctx_dup" ],
      [ "VTB", "structaltintegration_1_1VTB.html", "structaltintegration_1_1VTB" ],
      [ "WriteStream", "classaltintegration_1_1WriteStream.html", null ]
    ] ],
    [ "fmt", null, [
      [ "formatter< altintegration::Blob< N > >", "structfmt_1_1formatter_3_01altintegration_1_1Blob_3_01N_01_4_01_4.html", null ]
    ] ]
];