#ifndef ALT_INTEGRATION_TEST_UTIL_BLOCKCHAIN_FIXTURE_HPP_
#define ALT_INTEGRATION_TEST_UTIL_BLOCKCHAIN_FIXTURE_HPP_

namespace VeriBlock {

struct BlockchainFixture {

};

}

#endif  // ALT_INTEGRATION_TEST_UTIL_BLOCKCHAIN_FIXTURE_HPP_
