name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: checkout
      - run: mkdir -p build/docs/html
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: '.'
          doxyfile-path: './Doxyfile'
      - name: prepare
        run: |
          mv -f build/docs/html/* ./docs
      - name: publish
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_changes: Update docs ${{ github.sha }}
          branch: docs