name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: checkout
      - run: mkdir -p build/docs/html
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: '.'
          doxyfile-path: './Doxyfile'
      - name: prepare
        run: |
          sudo mv -f ./build/docs/html/* ./docs/
      - name: publish
        run: |
          git add .
          git commit -m "Update docs ${{ github.sha }}"
          git push -f