name: Dev Image CD

on:
  push:
    paths:
      - dev.Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Push
        uses: warchant/Publish-Docker-Github-Action@3
        with:
          name: veriblock/alt-integration-cpp-dev
          dockerfile: dev.Dockerfile
          username: ${{ secrets.PUBLIC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKERHUB_PASSWORD }}
          tag_names: true
