name: Fuzz (nightly)

# Job execution time - Each job in a workflow can run for up to 6 hours of execution time. If a job reaches this limit, the job is terminated and fails to complete.
#
# Workflow run time - Each workflow run is limited to 72 hours. If a workflow run reaches this limit, the workflow run is cancelled.

on:
  push:
    branches:
      - fuzz
  schedule:
    # run at the start of every 6th hour
    - cron:  '0 */6 * * *'

jobs:
  fuzz:
    runs-on: ubuntu-20.04
    env:
      # 5 hours in sec
      FUZZ_TIMEOUT: 30
      CC: clang
      CXX: clang++
      VBK_FUZZ_CORPUS_DIR: ${{ github.workspace }}/fuzz-corpus
    steps:
      - name: checkout alt-cpp
        uses: actions/checkout@v2
      - name: checkout fuzz-corpus
        uses: actions/checkout@v2
        with:
          repository: VeriBlock/fuzz-corpus
          path: ${{ github.workspace }}/fuzz-corpus
      - name: update apt-get
        run: sudo apt-get update
      - name: install new cmake
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install cmake
      - name: cmake
        run: >
          cmake . \
            -Bbuild \
            -DTESTING=OFF \
            -DFUZZING=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DFUZZ_TIMEOUT=${FUZZ_TIMEOUT}
      - name: build
        run: cmake --build build -- -j2 fuzz
      - name: commit corpus
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.FUZZ_CORPUS_SECRET }}
        with:
          user-email:  autogenerated@github.com
          destination-github-username: vbk-deploy
          destination-repository-username: VeriBlock
          destination-repository-name: fuzz-corpus
          commit-message: Update corpus ${{ github.sha }}
          target-branch: master
          source-directory: ${{ github.workspace }}/fuzz-corpus