name: CI (nightly)

# Job execution time - Each job in a workflow can run for up to 6 hours of execution time. If a job reaches this limit, the job is terminated and fails to complete.
#
# Workflow run time - Each workflow run is limited to 72 hours. If a workflow run reaches this limit, the workflow run is cancelled.

on:
  push:
    branches:
      - fuzz
  schedule:
    # run at the start of every 6th hour
    - cron:  '0 */6 * * *'

jobs:
  fuzz:
    runs-on: ubuntu-20.04
    env:
      # 5 hours in sec
      FUZZ_TIMEOUT: 18000
      CC: clang
      CXX: clang++
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: update apt-get
        run: sudo apt-get update
      - name: install new cmake
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install cmake
      - name: cmake
        run: >
          cmake . \
            -Bbuild \
            -DTESTING=OFF \
            -DFUZZING=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DFUZZ_TIMEOUT=${FUZZ_TIMEOUT} \
            -DN_PROCESSORS=1
      - name: build
        run: cmake --build build -- -j2 fuzz
